### ISSUE TITLE
Why does this REPO import gopkg.in/inf.v0

### ISSUE THREAD

**Issue by gshanemiller** [go-inf/inf#6]
The README.md needs a clarification so we aren't lost in almost-self-reference hell. The initial page for this REPO reads,

```
Package inf (type inf.Dec) implements "infinite-precision" decimal arithmetic. https://godoc.org/gopkg.in/inf.v0
```

but the package is called `inf` not `inf.v0` inside `go-inf` not `gopkg.in`. It seems like this package is NOT what people want. It seems like we need to go to https://gopkg.in/inf.v0 and following the link to https://github.com/go-inf/inf/tree/v0.9.1. But if you build this code it still imports `"gopkg.in/inf.v0` so it won't build anyway. 

What is the point of all this nonsense? Where is the code that satisfies:

```
package inf_test

import (
	"math/big"
	"testing"

	"gopkg.in/inf.v0"
)
```

inside say `inf/rounder_test.go` ? Are we supposed to clone `https://github.com/go-inf/inf/tree/v0.9.1` and put it into src tree as `.../src/gopkg.in/inf.v0` Why break the mold as this isn't how all other packages work?

**Comment by gshanemiller** [comment]
Note: I ran into this issue trying to build `gocql` The directive that

```
Refer to it as inf.
```

is unclear at https://gopkg.in/inf.v0. Why not just name it right in the first place?

Bottom line: the solution appears to be:

* clone https://github.com/go-inf/inf/tree/v0.9.1
* remove all references to "gopkg.in/inf.v0" and change to "inf"

which just asks the question of why the source doesn't ship like this?

**Comment by speter** [comment]
Thanks for the report. However I'm sorry but I don't really understand your
issue.

First, I have no issue building gocql including inf, either using go1.12.2
or go1.10.2:

$ ~/opt/go/bin/go get -v github.com/gocql/gocql
github.com/gocql/gocql (download)
github.com/golang/snappy (download)
github.com/hailocab/go-hostpool (download)
Fetching https://gopkg.in/inf.v0?go-get=1
Parsing meta tags from https://gopkg.in/inf.v0?go-get=1 (status code 200)
get "gopkg.in/inf.v0": found meta tag get.metaImport{Prefix:"gopkg.in/inf.v0",
VCS:"git", RepoRoot:"https://gopkg.in/inf.v0"} at
https://gopkg.in/inf.v0?go-get=1
gopkg.in/inf.v0 (download)
github.com/gocql/gocql/internal/lru
github.com/gocql/gocql/internal/murmur
github.com/gocql/gocql/internal/streams
github.com/golang/snappy
github.com/hailocab/go-hostpool
gopkg.in/inf.v0
github.com/gocql/gocql

$ ~/opt/go1.10/bin/go get -v github.com/gocql/gocql
github.com/gocql/gocql (download)
github.com/golang/snappy (download)
github.com/hailocab/go-hostpool (download)
Fetching https://gopkg.in/inf.v0?go-get=1
Parsing meta tags from https://gopkg.in/inf.v0?go-get=1 (status code 200)
get "gopkg.in/inf.v0": found meta tag get.metaImport{Prefix:"gopkg.in/inf.v0",
VCS:"git", RepoRoot:"https://gopkg.in/inf.v0"} at
https://gopkg.in/inf.v0?go-get=1
gopkg.in/inf.v0 (download)
github.com/gocql/gocql/internal/lru
github.com/gocql/gocql/internal/murmur
github.com/gocql/gocql/internal/streams
github.com/golang/snappy
github.com/hailocab/go-hostpool
gopkg.in/inf.v0
github.com/gocql/gocql

In addition note that gocql's travis build also has no problem building inf
with different versions of Go.

Second, what you're describing is just the way gopkg.in works (except for
the part "it won't build anyway" -- as you can see above it builds just
fine). The source is hosted on github but the import path is gopkg.in/inf.v0
. Are you suggesting that I should move off gopkg.in? I chose gopkg.in
because at the time, unlike go get with github import path, it had support
to introduce newer major versions in the same repo in the future. With
modules support in Go, this is no longer required, so I have been
considering to change it and might do it once module support is widespread.
But there's the question whether it's worth changing the import path
again...

Maybe if you could share the following it would be helpful in resolving
your issue:
1. what did you *exactly* do
2. what did you expect to happen
3. what happened actually (i.e. what *specific* error message did you get)

**Comment by speter** [comment]
Sorry I didn't notice until now that you had edited your comment above with more information. (It seems like Github doesn't send email notifications for edits.)

Note that the "solution" that you outline above is not the correct one. The correct way to get (download+build) the package is to run "go get gopkg.in/inf.v0", as described on the https://gopkg.in/inf.v0 page. You should never need to edit the source to change import paths.

It seems to me that for some reason you are trying to avoid "go get" and trying to replicate its behavior (incorrectly) -- this requires a bit more understanding of how "go get" works which can be less than straightforward in the existence of vanity imports and/or modules. If you *really* need to do this, I suggest that you study the relevant sections of https://golang.org/cmd/go/ in detail. Long story short, if you're using GOPATH, you need to clone the repo (at the right tag) to $GOPATH/src/gopkg.in/inf.v0 and then the import paths should "just work".

I will close this now as what you're describing seems to be working fine for the vast majority of users, but feel free to comment further if you need more information.
